version: 2.1
 orbs:
   sfdx: circleci/salesforce-sfdx@x.y
 jobs:
   install_authenticate:
     executor: sfdx/default
     steps:
       - checkout
       - sfdx/install
       - sfdx/auth:
           defaultusername: teresa.allen@brave-shark-3ic31k.com
       - run:
           name: Run your SFDX commands here
           command: |
             echo "You now have access to the sfdx cli and may execute commands against it. https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm"
 workflows:
   basic-test:
     jobs:
       - install_authenticate
